"""update orders and order_items

Revision ID: 0e278b4a5742
Revises: cc91bc359e7c
Create Date: 2025-12-15 13:56:47.190441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e278b4a5742'
down_revision: Union[str, Sequence[str], None] = 'cc91bc359e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('total', sa.Float(), nullable=False),
                    sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('payment_status',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'zip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order',
                    ['user_id'], unique=False)
    op.create_table('order_item',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('order_id', sa.Uuid(), nullable=False),
                    sa.Column('toy_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_order_item_order_id'),
                    'order_item', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
