"""fix circular import and models

Revision ID: 6bf2df274870
Revises: 315f94e34e1c
Create Date: 2025-12-10 09:34:35.154084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6bf2df274870'
down_revision: Union[str, Sequence[str], None] = '315f94e34e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_metadata',
                    sa.Column('toy_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('in_stock', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('toy_id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(
                        length=100), nullable=False),
                    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(
                        length=500), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('product_review',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('toy_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column(
                        'comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['toy_id'], ['product_metadata.toy_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_review')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('product_metadata')
    # ### end Alembic commands ###
