"""reverting to user table

Revision ID: 7c7c141712b6
Revises: 6bf2df274870
Create Date: 2025-12-10 11:23:06.356747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c7c141712b6'
down_revision: Union[str, Sequence[str], None] = '6bf2df274870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_review')
    op.drop_table('product_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_metadata',
    sa.Column('toy_id', sa.INTEGER(), server_default=sa.text("nextval('product_metadata_toy_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('toy_id', name='product_metadata_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('product_review',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('toy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['toy_id'], ['product_metadata.toy_id'], name=op.f('product_review_toy_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('product_review_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_review_pkey'))
    )
    # ### end Alembic commands ###
