"""add new relation, productstock and product

Revision ID: 8acf147839a3
Revises: eefdf38ee03d
Create Date: 2025-12-17 21:24:18.776222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8acf147839a3'
down_revision: Union[str, Sequence[str], None] = 'eefdf38ee03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'productstock', 'product', [
                          'toy_id'], ['toy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productstock', type_='foreignkey')
    # ### end Alembic commands ###
