"""update orders

Revision ID: aff472cb6ffe
Revises: 0e278b4a5742
Create Date: 2025-12-15 14:47:38.217708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aff472cb6ffe'
down_revision: Union[str, Sequence[str], None] = '0e278b4a5742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_status',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column('delivery_status',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column(
        'updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'delivery_status')
    op.drop_column('order', 'order_status')
    # ### end Alembic commands ###
