"""adding product_stock and review tables

Revision ID: c6bcc5a7a3c3
Revises: 160c8e23e980
Create Date: 2025-12-10 11:59:37.295424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6bcc5a7a3c3'
down_revision: Union[str, Sequence[str], None] = '160c8e23e980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productstock',
                    sa.Column('toy_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('toy_id')
                    )
    op.create_index(op.f('ix_productstock_toy_id'),
                    'productstock', ['toy_id'], unique=False)
    op.create_table('review',
                    sa.Column('review_id', sa.Integer(), nullable=False),
                    sa.Column('toy_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column(
                        'comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('review_id')
                    )
    op.create_index(op.f('ix_review_toy_id'),
                    'review', ['toy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_toy_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_productstock_toy_id'), table_name='productstock')
    op.drop_table('productstock')
    # ### end Alembic commands ###
