"""fix tables

Revision ID: d2d0dbcf67de
Revises: c6bcc5a7a3c3
Create Date: 2025-12-10 12:33:59.463665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd2d0dbcf67de'
down_revision: Union[str, Sequence[str], None] = 'c6bcc5a7a3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewmodel',
                    sa.Column('review_id', sa.Integer(), nullable=False),
                    sa.Column('toy_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column(
                        'comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('review_id')
                    )
    op.create_index(op.f('ix_reviewmodel_toy_id'),
                    'reviewmodel', ['toy_id'], unique=False)
    op.create_table('usermodel',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(
                        length=100), nullable=False),
                    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(
                        length=500), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_usermodel_email'),
                    'usermodel', ['email'], unique=True)
    op.create_index(op.f('ix_usermodel_id'), 'usermodel', ['id'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_review_toy_id'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
                    sa.Column('review_id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('toy_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('rating', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('comment', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'review_id', name=op.f('review_pkey'))
                    )
    op.create_index(op.f('ix_review_toy_id'),
                    'review', ['toy_id'], unique=False)
    op.create_table('user',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('hashed_password', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('image_url', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=True),
                    sa.Column('is_active', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('is_deleted', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
                    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_usermodel_id'), table_name='usermodel')
    op.drop_index(op.f('ix_usermodel_email'), table_name='usermodel')
    op.drop_table('usermodel')
    op.drop_index(op.f('ix_reviewmodel_toy_id'), table_name='reviewmodel')
    op.drop_table('reviewmodel')
    # ### end Alembic commands ###
