"""add product age_group and product_type tables

Revision ID: eefdf38ee03d
Revises: 8dec9bc486f5
Create Date: 2025-12-17 21:20:10.787277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'eefdf38ee03d'
down_revision: Union[str, Sequence[str], None] = '8dec9bc486f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_group',
                    sa.Column('age_group_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('age_group_id')
                    )
    op.create_table('product_type',
                    sa.Column('type_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('type_id')
                    )
    op.create_table('product',
                    sa.Column('toy_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('permalink', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('target_group', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('production_date', sa.Date(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('age_group_id', sa.Integer(), nullable=False),
                    sa.Column('type_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['age_group_id'], ['age_group.age_group_id'], ),
                    sa.ForeignKeyConstraint(
                        ['type_id'], ['product_type.type_id'], ),
                    sa.PrimaryKeyConstraint('toy_id')
                    )
    op.create_index(op.f('ix_product_toy_id'),
                    'product', ['toy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_toy_id'), table_name='product')
    op.drop_table('product')
    op.drop_table('product_type')
    op.drop_table('age_group')
    # ### end Alembic commands ###
